src/java/polman/model/TrCup.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polman.model;

import java.io.Serializable;
import java.util.Collection;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 *
 * @author Candra
 */
@Entity
@Table(name = "tr_Cup")
@NamedQueries({
    @NamedQuery(name = "TrCup.findAll", query = "SELECT t FROM TrCup t")
    , @NamedQuery(name = "TrCup.findByCupId", query = "SELECT t FROM TrCup t WHERE t.cupId = :cupId")
    , @NamedQuery(name = "TrCup.findByCupNamakompetisi", query = "SELECT t FROM TrCup t WHERE t.cupNamakompetisi = :cupNamakompetisi")
    , @NamedQuery(name = "TrCup.findByCupPenyelenggara", query = "SELECT t FROM TrCup t WHERE t.cupPenyelenggara = :cupPenyelenggara")
    , @NamedQuery(name = "TrCup.findByCupMulai", query = "SELECT t FROM TrCup t WHERE t.cupMulai = :cupMulai")
    , @NamedQuery(name = "TrCup.findByCupAkhir", query = "SELECT t FROM TrCup t WHERE t.cupAkhir = :cupAkhir")
    , @NamedQuery(name = "TrCup.findByCupCreatedby", query = "SELECT t FROM TrCup t WHERE t.cupCreatedby = :cupCreatedby")
    , @NamedQuery(name = "TrCup.findByCupModivedby", query = "SELECT t FROM TrCup t WHERE t.cupModivedby = :cupModivedby")
    , @NamedQuery(name = "TrCup.findByCupCreateddate", query = "SELECT t FROM TrCup t WHERE t.cupCreateddate = :cupCreateddate")
    , @NamedQuery(name = "TrCup.findByCupModiveddate", query = "SELECT t FROM TrCup t WHERE t.cupModiveddate = :cupModiveddate")})
public class TrCup implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "cup_id",columnDefinition="int(1,1)")
    private Integer cupId;
    @Size(max = 100)
    @Column(name = "cup_namakompetisi")
    private String cupNamakompetisi;
    @Size(max = 50)
    @Column(name = "cup_penyelenggara")
    private String cupPenyelenggara;
    @Column(name = "cup_mulai")
    @Temporal(TemporalType.DATE)
    private Date cupMulai;
    @Column(name = "cup_akhir")
    @Temporal(TemporalType.DATE)
    private Date cupAkhir;
    @Size(max = 50)
    @Column(name = "cup_createdby")
    private String cupCreatedby;
    @Size(max = 50)
    @Column(name = "cup_modivedby")
    private String cupModivedby;
    @Column(name = "cup_createddate")
    @Temporal(TemporalType.DATE)
    private Date cupCreateddate;
    @Column(name = "cup_modiveddate")
    @Temporal(TemporalType.DATE)
    private Date cupModiveddate;
    @OneToMany(mappedBy = "jadCupId")
    private Collection<TrJadwal> trJadwalCollection;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "trCup")
    private Collection<TrdtlPrestasiPemain> trdtlPrestasiPemainCollection;

    public TrCup() {
    }

    public TrCup(Integer cupId) {
        this.cupId = cupId;
    }

    public Integer getCupId() {
        return cupId;
    }

    public void setCupId(Integer cupId) {
        this.cupId = cupId;
    }

    public String getCupNamakompetisi() {
        return cupNamakompetisi;
    }

    public void setCupNamakompetisi(String cupNamakompetisi) {
        this.cupNamakompetisi = cupNamakompetisi;
    }

    public String getCupPenyelenggara() {
        return cupPenyelenggara;
    }

    public void setCupPenyelenggara(String cupPenyelenggara) {
        this.cupPenyelenggara = cupPenyelenggara;
    }

    public Date getCupMulai() {
        return cupMulai;
    }

    public void setCupMulai(Date cupMulai) {
        this.cupMulai = cupMulai;
    }

    public Date getCupAkhir() {
        return cupAkhir;
    }

    public void setCupAkhir(Date cupAkhir) {
        this.cupAkhir = cupAkhir;
    }

    public String getCupCreatedby() {
        return cupCreatedby;
    }

    public void setCupCreatedby(String cupCreatedby) {
        this.cupCreatedby = cupCreatedby;
    }

    public String getCupModivedby() {
        return cupModivedby;
    }

    public void setCupModivedby(String cupModivedby) {
        this.cupModivedby = cupModivedby;
    }

    public Date getCupCreateddate() {
        return cupCreateddate;
    }

    public void setCupCreateddate(Date cupCreateddate) {
        this.cupCreateddate = cupCreateddate;
    }

    public Date getCupModiveddate() {
        return cupModiveddate;
    }

    public void setCupModiveddate(Date cupModiveddate) {
        this.cupModiveddate = cupModiveddate;
    }

    public Collection<TrJadwal> getTrJadwalCollection() {
        return trJadwalCollection;
    }

    public void setTrJadwalCollection(Collection<TrJadwal> trJadwalCollection) {
        this.trJadwalCollection = trJadwalCollection;
    }

    public Collection<TrdtlPrestasiPemain> getTrdtlPrestasiPemainCollection() {
        return trdtlPrestasiPemainCollection;
    }

    public void setTrdtlPrestasiPemainCollection(Collection<TrdtlPrestasiPemain> trdtlPrestasiPemainCollection) {
        this.trdtlPrestasiPemainCollection = trdtlPrestasiPemainCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (cupId != null ? cupId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof TrCup)) {
            return false;
        }
        TrCup other = (TrCup) object;
        if ((this.cupId == null && other.cupId != null) || (this.cupId != null && !this.cupId.equals(other.cupId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "polman.model.TrCup[ cupId=" + cupId + " ]";
    }
    
}

src/java/polman/view/TrCupController.java
package polman.view;

import java.io.IOException;
import polman.model.TrCup;
import polman.view.util.JsfUtil;
import polman.view.util.PaginationHelper;
import polman.controller.TrCupFacade;

import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.application.NavigationHandler;
import javax.faces.component.UIComponent;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import org.primefaces.context.RequestContext;
import org.primefaces.event.SelectEvent;

@Named("trCupController")
@SessionScoped
public class TrCupController implements Serializable {

    private TrCup current;
    private DataModel items = null;
    @EJB
    private polman.controller.TrCupFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public TrCupController() {
    }

    
    public TrCup getSelected() {
        if (current == null) {
            current = new TrCup();
            selectedItemIndex = -1;
        }
        return current;
    }
    Date min;

    public Date getMin() {
        return min;
    }

    public void setMin(Date min) {
        this.min = min;
    }
    public void onDateSelect(SelectEvent event) {
        FacesContext facesContext = FacesContext.getCurrentInstance();
        SimpleDateFormat format = new SimpleDateFormat("dd MMMMM yyyy");
        try {
            min = format.parse( format.format(event.getObject()));
        } catch (ParseException ex) {
            Logger.getLogger(TrCupController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private TrCupFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (TrCup) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new TrCup();
        selectedItemIndex = -1;
        return "List";
    }

    public String create() {
        try {
            
            getFacade().create(current);
            current = new TrCup();
            selectedItemIndex = -1;
            return "List";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }
    boolean showAlert = false;

    public boolean isShowAlert() {
        return showAlert;
    }

    public void setShowAlert(boolean showAlert) {
        this.showAlert = showAlert;
    }
    Date date1;

    public Date getDate1() {
        return date1;
    }

    public void setDate1(Date date1) {
        this.date1 = date1;
    }
    int idCup;

    public int getIdCup() {
        return idCup;
    }

    public void setIdCup(int idCup) {
        this.idCup = idCup;
    }
    
    public String prepareEdit() throws IOException {
//        current = (TrCup) getItems().getRowData();
        current = ejbFacade.find(idCup);
        hapus=false;
        Date a = new Date();
        if(current.getCupMulai().after(a))
        {
            showAlert = false;
            return "Edit.xhtml?faces-redirect=true";
//            FacesContext facesContext = FacesContext.getCurrentInstance();
//            String redirect = "Edit";
//            NavigationHandler myNav = facesContext.getApplication().getNavigationHandler();
//            myNav.handleNavigation(facesContext, null, redirect);
        }
        else
        {
            
            showAlert = true;
            
            return null;
            
        }
        
         
        //return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            current = new TrCup();
            selectedItemIndex = -1;
            return "List";
        } catch (Exception e) {
            return null;
        }
    }
    boolean hapus = false;

    public boolean isHapus() {
        return hapus;
    }

    public void setHapus(boolean hapus) {
        this.hapus = hapus;
    }
    
    public String destroy() {
        current = ejbFacade.find(idCup);
        Date a = new Date();
        showAlert = false;
        if(current.getCupMulai().after(a))
        {
            
            getFacade().remove(current);
            recreatePagination();
            recreateModel();
            hapus = false;
            
        }
        else
        {
            
            hapus = true;
            return null;
            
        }
        
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TrCupDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }
    public List getDaftarKompetisi()
    {
        List a = ejbFacade.findAll();
        return a;
    }
    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public TrCup getTrCup(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = TrCup.class)
    public static class TrCupControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            TrCupController controller = (TrCupController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "trCupController");
            return controller.getTrCup(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof TrCup) {
                TrCup o = (TrCup) object;
                return getStringKey(o.getCupId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + TrCup.class.getName());
            }
        }

    }

}

web/trCup/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    
    <h:body>
     <ui:composition template="../TemplatePage.xhtml">
        
        <ui:define name="contentheader">
            <h:outputText value="Kompetisi"></h:outputText>
        </ui:define>
        <ui:define name="contenttitle">
            <h:outputText value="Tambah Kompetisi Baru"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <center><h:form >
                <h:panelGrid columns="5" >
                    <h:outputLabel value="Nama Kompetisi" for="namaMenu" />
                    &nbsp;&nbsp;&nbsp;&nbsp;<h:inputText class="form-control" validatorMessage="Nama kompetisi harus huruf" required="true" 
                                                         requiredMessage="Nama kompetisi tidak bisa kosong" id="namaMenu" value="#{trCupController.selected.cupNamakompetisi}" title="Nama Kompetisi" >
                        <f:validateRegex pattern="[a-zA-Z ]+" />
                    </h:inputText>
                    &nbsp;<h:message for="namaMenu" errorStyle="color: red"/>
                    
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />

                    <h:outputLabel value="Penyelenggara Kompetisi" for="keterangan" />
                    &nbsp;<h:inputText class="form-control" validatorMessage="Nama penyelenggara kompetisi harus huruf" required="true" 
                                       requiredMessage="Nama penyelenggara kompetisi tidak bisa kosong" id="keterangan" value="#{trCupController.selected.cupPenyelenggara}" title="Penyelenggara Kompetisi" >
                        <f:validateRegex pattern="[a-zA-Z ]+" />
                    </h:inputText>
                    &nbsp;<h:message for="keterangan" errorStyle="color: red"/>
                    
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />

                    <h:outputLabel value="Tanggal Mulai" for="harga" />
                    &nbsp;<p:calendar id="idStartDate" readonlyInput="true"
                                      value="#{trCupController.selected.cupMulai}" requiredMessage="Tanggal mulai tidak bisa kosong" title="Tanggal Mulai"
                                       navigator="true" pattern="dd MMMMM yyyy">
                        <p:ajax event="dateSelect" update="idEndDate" />
                    </p:calendar>
                
                    &nbsp;<h:message for="harga" errorStyle="color: red"/>

                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    
                    <h:outputLabel value="Tanggal Selesai" for="cepatBasi" />
                    &nbsp;<p:calendar id="idEndDate" readonlyInput="true"
                                      value="#{trCupController.selected.cupAkhir}"
                                      mindate="#{trCupController.selected.cupMulai}"  requiredMessage="Tanggal selesai tidak bisa kosong" 
                                      title="Tanggal Selesai"  navigator="true" pattern="dd MMMMM yyyy">
                        <p:ajax event="dateSelect"/>
                    </p:calendar>
                    &nbsp;<h:message for="cepatBasi" errorStyle="color: red"/>
                    
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    
                    
                </h:panelGrid>
                <br />
                <h:commandButton class="flat btn-primary" style="width: 100px;height: 30px" action="#{trCupController.create}" value="Tambah Kompetisi Baru" />
            </h:form></center>
            
        </ui:define>
    </ui:composition>
</h:body>
</html>

web/trCup/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="../TemplatePage.xhtml">
        
        <ui:define name="contentheader">
            <h:outputText value="Kompetisi"></h:outputText>
        </ui:define>
        <ui:define name="contenttitle">
            <h:outputText value="Tambah Kompetisi Baru"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <center><h:form >
                <h:panelGrid columns="5" >
                    <h:outputLabel value="Nama Kompetisi" for="namaMenu" />
                    &nbsp;&nbsp;&nbsp;&nbsp;<h:inputText class="form-control" validatorMessage="Nama komepetisi harus huruf" required="true" 
                                                         requiredMessage="Nama kompetisi tidak bisa kosong" id="namaMenu" value="#{trCupController.selected.cupNamakompetisi}" title="Nama Kompetisi" >
                        <f:validateRegex pattern="[a-zA-Z ]+" />
                    </h:inputText>
                    &nbsp;<h:message for="namaMenu" errorStyle="color: red"/>
                    
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />

                    <h:outputLabel value="Penyelenggara Kompetisi" for="keterangan" />
                    &nbsp;<h:inputText class="form-control" validatorMessage="Nama penyelenggara kompetisi harus huruf" required="true" 
                                       requiredMessage="Nama penyelenggara kompetisi tidak bisa kosong" id="keterangan" value="#{trCupController.selected.cupPenyelenggara}" title="Penyelenggara Kompetisi" >
                        <f:validateRegex pattern="[a-zA-Z ]+" />
                    </h:inputText>
                    &nbsp;<h:message for="keterangan" errorStyle="color: red"/>
                    
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />

                    <h:outputLabel value="Tanggal Mulai" for="idStartDate" />
                    &nbsp;<p:calendar id="idStartDate" readonlyInput="true"
                                      value="#{trCupController.selected.cupMulai}" requiredMessage="Tanggal mulai tidak bisa kosong" title="Tanggal Mulai"
                                       navigator="true" pattern="dd MMMMM yyyy">
                        <p:ajax event="dateSelect" update="idEndDate" />
                    </p:calendar>
                
                    &nbsp;<h:message for="harga" errorStyle="color: red"/>

                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    
                    <h:outputLabel value="Tanggal Selesai" for="idEndDate" />
                    &nbsp;<p:calendar id="idEndDate" readonlyInput="true"
                                      value="#{trCupController.selected.cupAkhir}"
                                      mindate="#{trCupController.selected.cupMulai}"  requiredMessage="Tangal selesai tidak bisa kosong" 
                                      title="Tanggal Selesai"  navigator="true" pattern="dd MMMMM yyyy">
                        <p:ajax event="dateSelect"/>
                    </p:calendar>
                    &nbsp;<h:message for="cepatBasi" errorStyle="color: red"/>
                    
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    <h:outputLabel value="" for="namaMenu" />
                    
                    
                </h:panelGrid>
                <br />
                <h:commandButton class="flat btn-primary" style="width: 100px;height: 30px" action="#{trCupController.update}" value="Ubah Data Kompetisi" />
            </h:form></center>
            
        </ui:define>
    </ui:composition>

</html>

web/trCup/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="../TemplatePage.xhtml">
        
        <ui:define name="contentheader">
            <h:outputText value="Kompetisi"></h:outputText>
        </ui:define>
        <ui:define name="contenttitle">
            <h:outputText value="Daftar Kompetisi"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <h:form>
                <table id="example1" class="table table-bordered table-striped dataTable table-hover">
                    <thead>
                        <tr>
                            <th>Nama Kompetisi</th>
                            <th>Penyelenggara Kompetisi</th>
                            <th>Tanggal Mulai</th>
                            <th>Tanggal Selesai</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        <ui:repeat var="item" value="#{trCupController.daftarKompetisi}">
                            <tr> 
                                <td><h:outputText value="#{item.cupNamakompetisi}"/></td>
                                <td><h:outputText value="#{item.cupPenyelenggara}"/></td>
                                <td><h:outputText value="#{item.cupMulai}" >
                                    <f:convertDateTime timeZone="GMT+7" pattern="dd MMMMM yyyy" />
                                </h:outputText></td>
                                <td><h:outputText value="#{item.cupMulai}" >
                                    <f:convertDateTime timeZone="GMT+7" pattern="dd MMMMM yyyy" />
                                </h:outputText></td>
                                <td><h:commandButton class="btn btn-primary btn-flat" action="#{trCupController.prepareEdit}" value="Ubah" >
                                        <f:setPropertyActionListener target="#{trCupController.idCup}" value="#{item.cupId}"/>
                                    </h:commandButton> &nbsp;&nbsp;&nbsp;&nbsp;
                                    <h:commandButton class="btn btn-primary btn-flat" action="#{trCupController.destroy}" value="Hapus" >
                                        <f:setPropertyActionListener target="#{trCupController.idCup}" value="#{item.cupId}"/>
                                    </h:commandButton></td>
                            </tr>
                        </ui:repeat>
                            
                    </tbody>
                </table>
               
                
               
                <h:outputScript rendered="#{trCupController.showAlert}">
                    alert("Kompetisi tidak bisa di ubah");
                 </h:outputScript>
                <h:outputScript rendered="#{trCupController.hapus}">
                    alert("Kompetisi tidak bisa di hapus");
                 </h:outputScript>
                
                
                
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/trCup/Report_1.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
<h:head>
        <meta charset="utf-8" />
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic"/>
    </h:head>
    <h:body>
    <ui:composition template="../TemplatePage.xhtml">
        <ui:define name="contentheader">
            <h:outputText value="Menu"></h:outputText>
        </ui:define>
        <ui:define name="contenttitle">
            <h:outputText value="Laporan Belanja"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <center>
                <f:event type="preRenderView" listener="#{trCupController.prepareEdit2}" />
            </center>
        </ui:define>
    </ui:composition>
    </h:body>
</html>