src/java/polman/model/TrdtlPertandingan.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package polman.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 *
 * @author Candra
 */
@Entity
@Table(name = "tr_dtlPertandingan")
@NamedQueries({
    @NamedQuery(name = "TrdtlPertandingan.findAll", query = "SELECT t FROM TrdtlPertandingan t")
    , @NamedQuery(name = "TrdtlPertandingan.findByDtsIdjad", query = "SELECT t FROM TrdtlPertandingan t WHERE t.trdtlPertandinganPK.dtsIdjad = :dtsIdjad")
    , @NamedQuery(name = "TrdtlPertandingan.findByDtsIdpem", query = "SELECT t FROM TrdtlPertandingan t WHERE t.trdtlPertandinganPK.dtsIdpem = :dtsIdpem")
    , @NamedQuery(name = "TrdtlPertandingan.findByMenit", query = "SELECT t FROM TrdtlPertandingan t WHERE t.menit = :menit")
    , @NamedQuery(name = "TrdtlPertandingan.findByDtsPelanggaran", query = "SELECT t FROM TrdtlPertandingan t WHERE t.dtsPelanggaran = :dtsPelanggaran")
    , @NamedQuery(name = "TrdtlPertandingan.findByDtsTangkap", query = "SELECT t FROM TrdtlPertandingan t WHERE t.dtsTangkap = :dtsTangkap")
    , @NamedQuery(name = "TrdtlPertandingan.findByDtsLolos", query = "SELECT t FROM TrdtlPertandingan t WHERE t.dtsLolos = :dtsLolos")})
public class TrdtlPertandingan implements Serializable {

    private static final long serialVersionUID = 1L;
    @EmbeddedId
    protected TrdtlPertandinganPK trdtlPertandinganPK;
    @Basic(optional = false)
    @NotNull
    @Column(name = "menit")
    @Temporal(TemporalType.TIME)
    private Date menit;
    @Column(name = "dts_pelanggaran")
    private Integer dtsPelanggaran;
    @Column(name = "dts_tangkap")
    private Integer dtsTangkap;
    @Column(name = "dts_lolos")
    private Integer dtsLolos;
    @JoinColumn(name = "dts_idpem", referencedColumnName = "pes_id", insertable = false, updatable = false)
    @ManyToOne(optional = false)
    private MsPeserta msPeserta;
    @JoinColumn(name = "dts_idjad", referencedColumnName = "jad_id", insertable = false, updatable = false)
    @ManyToOne(optional = false)
    private TrJadwal trJadwal;

    public TrdtlPertandingan() {
    }

    public TrdtlPertandingan(TrdtlPertandinganPK trdtlPertandinganPK) {
        this.trdtlPertandinganPK = trdtlPertandinganPK;
    }

    public TrdtlPertandingan(TrdtlPertandinganPK trdtlPertandinganPK, Date menit) {
        this.trdtlPertandinganPK = trdtlPertandinganPK;
        this.menit = menit;
    }

    public TrdtlPertandingan(int dtsIdjad, int dtsIdpem) {
        this.trdtlPertandinganPK = new TrdtlPertandinganPK(dtsIdjad, dtsIdpem);
    }

    public TrdtlPertandinganPK getTrdtlPertandinganPK() {
        return trdtlPertandinganPK;
    }

    public void setTrdtlPertandinganPK(TrdtlPertandinganPK trdtlPertandinganPK) {
        this.trdtlPertandinganPK = trdtlPertandinganPK;
    }

    public Date getMenit() {
        return menit;
    }

    public void setMenit(Date menit) {
        this.menit = menit;
    }

    public Integer getDtsPelanggaran() {
        return dtsPelanggaran;
    }

    public void setDtsPelanggaran(Integer dtsPelanggaran) {
        this.dtsPelanggaran = dtsPelanggaran;
    }

    public Integer getDtsTangkap() {
        return dtsTangkap;
    }

    public void setDtsTangkap(Integer dtsTangkap) {
        this.dtsTangkap = dtsTangkap;
    }

    public Integer getDtsLolos() {
        return dtsLolos;
    }

    public void setDtsLolos(Integer dtsLolos) {
        this.dtsLolos = dtsLolos;
    }

    public MsPeserta getMsPeserta() {
        return msPeserta;
    }

    public void setMsPeserta(MsPeserta msPeserta) {
        this.msPeserta = msPeserta;
    }

    public TrJadwal getTrJadwal() {
        return trJadwal;
    }

    public void setTrJadwal(TrJadwal trJadwal) {
        this.trJadwal = trJadwal;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (trdtlPertandinganPK != null ? trdtlPertandinganPK.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof TrdtlPertandingan)) {
            return false;
        }
        TrdtlPertandingan other = (TrdtlPertandingan) object;
        if ((this.trdtlPertandinganPK == null && other.trdtlPertandinganPK != null) || (this.trdtlPertandinganPK != null && !this.trdtlPertandinganPK.equals(other.trdtlPertandinganPK))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "polman.model.TrdtlPertandingan[ trdtlPertandinganPK=" + trdtlPertandinganPK + " ]";
    }
    
}

src/java/polman/view/TrdtlPertandinganController.java
package polman.view;

import polman.model.TrdtlPertandingan;
import polman.view.util.JsfUtil;
import polman.view.util.PaginationHelper;
import polman.controller.TrdtlPertandinganFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("trdtlPertandinganController")
@SessionScoped
public class TrdtlPertandinganController implements Serializable {

    private TrdtlPertandingan current;
    private DataModel items = null;
    @EJB
    private polman.controller.TrdtlPertandinganFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public TrdtlPertandinganController() {
    }

    public TrdtlPertandingan getSelected() {
        if (current == null) {
            current = new TrdtlPertandingan();
            current.setTrdtlPertandinganPK(new polman.model.TrdtlPertandinganPK());
            selectedItemIndex = -1;
        }
        return current;
    }

    private TrdtlPertandinganFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (TrdtlPertandingan) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new TrdtlPertandingan();
        current.setTrdtlPertandinganPK(new polman.model.TrdtlPertandinganPK());
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            current.getTrdtlPertandinganPK().setDtsIdjad(current.getTrJadwal().getJadId());
            current.getTrdtlPertandinganPK().setDtsIdpem(current.getMsPeserta().getPesId());
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TrdtlPertandinganCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (TrdtlPertandingan) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            current.getTrdtlPertandinganPK().setDtsIdjad(current.getTrJadwal().getJadId());
            current.getTrdtlPertandinganPK().setDtsIdpem(current.getMsPeserta().getPesId());
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TrdtlPertandinganUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (TrdtlPertandingan) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TrdtlPertandinganDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public TrdtlPertandingan getTrdtlPertandingan(polman.model.TrdtlPertandinganPK id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = TrdtlPertandingan.class)
    public static class TrdtlPertandinganControllerConverter implements Converter {

        private static final String SEPARATOR = "#";
        private static final String SEPARATOR_ESCAPED = "\\#";

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            TrdtlPertandinganController controller = (TrdtlPertandinganController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "trdtlPertandinganController");
            return controller.getTrdtlPertandingan(getKey(value));
        }

        polman.model.TrdtlPertandinganPK getKey(String value) {
            polman.model.TrdtlPertandinganPK key;
            String values[] = value.split(SEPARATOR_ESCAPED);
            key = new polman.model.TrdtlPertandinganPK();
            key.setDtsIdjad(Integer.parseInt(values[0]));
            key.setDtsIdpem(Integer.parseInt(values[1]));
            return key;
        }

        String getStringKey(polman.model.TrdtlPertandinganPK value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value.getDtsIdjad());
            sb.append(SEPARATOR);
            sb.append(value.getDtsIdpem());
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof TrdtlPertandingan) {
                TrdtlPertandingan o = (TrdtlPertandingan) object;
                return getStringKey(o.getTrdtlPertandinganPK());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + TrdtlPertandingan.class.getName());
            }
        }

    }

}

web/trdtlPertandingan/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateTrdtlPertandinganTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateTrdtlPertandinganLabel_menit}" for="menit" />
                    <h:inputText id="menit" value="#{trdtlPertandinganController.selected.menit}" title="#{bundle.CreateTrdtlPertandinganTitle_menit}" required="true" requiredMessage="#{bundle.CreateTrdtlPertandinganRequiredMessage_menit}">
                        <f:convertDateTime pattern="HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.CreateTrdtlPertandinganLabel_dtsPelanggaran}" for="dtsPelanggaran" />
                    <h:inputText id="dtsPelanggaran" value="#{trdtlPertandinganController.selected.dtsPelanggaran}" title="#{bundle.CreateTrdtlPertandinganTitle_dtsPelanggaran}" />
                    <h:outputLabel value="#{bundle.CreateTrdtlPertandinganLabel_dtsTangkap}" for="dtsTangkap" />
                    <h:inputText id="dtsTangkap" value="#{trdtlPertandinganController.selected.dtsTangkap}" title="#{bundle.CreateTrdtlPertandinganTitle_dtsTangkap}" />
                    <h:outputLabel value="#{bundle.CreateTrdtlPertandinganLabel_dtsLolos}" for="dtsLolos" />
                    <h:inputText id="dtsLolos" value="#{trdtlPertandinganController.selected.dtsLolos}" title="#{bundle.CreateTrdtlPertandinganTitle_dtsLolos}" />
                    <h:outputLabel value="#{bundle.CreateTrdtlPertandinganLabel_msPeserta}" for="msPeserta" />
                    <h:selectOneMenu id="msPeserta" value="#{trdtlPertandinganController.selected.msPeserta}" title="#{bundle.CreateTrdtlPertandinganTitle_msPeserta}" required="true" requiredMessage="#{bundle.CreateTrdtlPertandinganRequiredMessage_msPeserta}">
                        <f:selectItems value="#{msPesertaController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateTrdtlPertandinganLabel_trJadwal}" for="trJadwal" />
                    <h:selectOneMenu id="trJadwal" value="#{trdtlPertandinganController.selected.trJadwal}" title="#{bundle.CreateTrdtlPertandinganTitle_trJadwal}" required="true" requiredMessage="#{bundle.CreateTrdtlPertandinganRequiredMessage_trJadwal}">
                        <f:selectItems value="#{trJadwalController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{trdtlPertandinganController.create}" value="#{bundle.CreateTrdtlPertandinganSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{trdtlPertandinganController.prepareList}" value="#{bundle.CreateTrdtlPertandinganShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateTrdtlPertandinganIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/trdtlPertandingan/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditTrdtlPertandinganTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditTrdtlPertandinganLabel_menit}" for="menit" />
                    <h:inputText id="menit" value="#{trdtlPertandinganController.selected.menit}" title="#{bundle.EditTrdtlPertandinganTitle_menit}" required="true" requiredMessage="#{bundle.EditTrdtlPertandinganRequiredMessage_menit}">
                        <f:convertDateTime pattern="HH:mm:ss" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditTrdtlPertandinganLabel_dtsPelanggaran}" for="dtsPelanggaran" />
                    <h:inputText id="dtsPelanggaran" value="#{trdtlPertandinganController.selected.dtsPelanggaran}" title="#{bundle.EditTrdtlPertandinganTitle_dtsPelanggaran}" />
                    <h:outputLabel value="#{bundle.EditTrdtlPertandinganLabel_dtsTangkap}" for="dtsTangkap" />
                    <h:inputText id="dtsTangkap" value="#{trdtlPertandinganController.selected.dtsTangkap}" title="#{bundle.EditTrdtlPertandinganTitle_dtsTangkap}" />
                    <h:outputLabel value="#{bundle.EditTrdtlPertandinganLabel_dtsLolos}" for="dtsLolos" />
                    <h:inputText id="dtsLolos" value="#{trdtlPertandinganController.selected.dtsLolos}" title="#{bundle.EditTrdtlPertandinganTitle_dtsLolos}" />
                    <h:outputLabel value="#{bundle.EditTrdtlPertandinganLabel_msPeserta}" for="msPeserta" />
                    <h:selectOneMenu id="msPeserta" value="#{trdtlPertandinganController.selected.msPeserta}" title="#{bundle.EditTrdtlPertandinganTitle_msPeserta}" required="true" requiredMessage="#{bundle.EditTrdtlPertandinganRequiredMessage_msPeserta}">
                        <f:selectItems value="#{msPesertaController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditTrdtlPertandinganLabel_trJadwal}" for="trJadwal" />
                    <h:selectOneMenu id="trJadwal" value="#{trdtlPertandinganController.selected.trJadwal}" title="#{bundle.EditTrdtlPertandinganTitle_trJadwal}" required="true" requiredMessage="#{bundle.EditTrdtlPertandinganRequiredMessage_trJadwal}">
                        <f:selectItems value="#{trJadwalController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{trdtlPertandinganController.update}" value="#{bundle.EditTrdtlPertandinganSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditTrdtlPertandinganViewLink}"/>
                <br />
                <h:commandLink action="#{trdtlPertandinganController.prepareList}" value="#{bundle.EditTrdtlPertandinganShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditTrdtlPertandinganIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/trdtlPertandingan/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListTrdtlPertandinganTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListTrdtlPertandinganEmpty}" rendered="#{trdtlPertandinganController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{trdtlPertandinganController.items.rowCount > 0}">
                    <h:outputText value="#{trdtlPertandinganController.pagination.pageFirstItem + 1}..#{trdtlPertandinganController.pagination.pageLastItem + 1}/#{trdtlPertandinganController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{trdtlPertandinganController.previous}" value="#{bundle.Previous} #{trdtlPertandinganController.pagination.pageSize}" rendered="#{trdtlPertandinganController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{trdtlPertandinganController.next}" value="#{bundle.Next} #{trdtlPertandinganController.pagination.pageSize}" rendered="#{trdtlPertandinganController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{trdtlPertandinganController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTrdtlPertandinganTitle_menit}"/>
                            </f:facet>
                            <h:outputText value="#{item.menit}">
                                <f:convertDateTime pattern="HH:mm:ss" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTrdtlPertandinganTitle_dtsPelanggaran}"/>
                            </f:facet>
                            <h:outputText value="#{item.dtsPelanggaran}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTrdtlPertandinganTitle_dtsTangkap}"/>
                            </f:facet>
                            <h:outputText value="#{item.dtsTangkap}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTrdtlPertandinganTitle_dtsLolos}"/>
                            </f:facet>
                            <h:outputText value="#{item.dtsLolos}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTrdtlPertandinganTitle_msPeserta}"/>
                            </f:facet>
                            <h:outputText value="#{item.msPeserta}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListTrdtlPertandinganTitle_trJadwal}"/>
                            </f:facet>
                            <h:outputText value="#{item.trJadwal}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{trdtlPertandinganController.prepareView}" value="#{bundle.ListTrdtlPertandinganViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{trdtlPertandinganController.prepareEdit}" value="#{bundle.ListTrdtlPertandinganEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{trdtlPertandinganController.destroy}" value="#{bundle.ListTrdtlPertandinganDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{trdtlPertandinganController.prepareCreate}" value="#{bundle.ListTrdtlPertandinganCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListTrdtlPertandinganIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>