src/java/polman/view/TrBeritaController.java
package polman.view;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import polman.model.TrBerita;
import polman.view.util.JsfUtil;
import polman.view.util.PaginationHelper;
import polman.controller.TrBeritaFacade;

import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import polman.controller.TrGambarBeritaFacade;
import polman.model.TrGambarBerita;

@Named("trBeritaController")
@SessionScoped
public class TrBeritaController implements Serializable {

    private EntityManagerFactory emf = Persistence.createEntityManagerFactory("GobakSodorPU");
    private EntityManager em = emf.createEntityManager();
    private int idberita,idBeritaDetail;
    private TrBerita current;
    private DataModel items = null;
    @EJB
    private polman.controller.TrBeritaFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;
    boolean hapus;

    public int getIdBeritaDetail() {
        return idBeritaDetail;
    }

    public TrBeritaFacade getEjbFacade() {
        return ejbFacade;
    }

    public void setEjbFacade(TrBeritaFacade ejbFacade) {
        this.ejbFacade = ejbFacade;
    }
    
    
    public void setIdBeritaDetail(int idBeritaDetail) {
        this.idBeritaDetail = idBeritaDetail;
    }
    
    public String baca()
    {
        current = ejbFacade.find(idBeritaDetail);
        current.setBerPengunjung(current.getBerPengunjung()+1);
        ejbFacade.edit(current);
        return "bacaberita";
    }
    public boolean isHapus() {
        return hapus;
    }

    public void setHapus(boolean hapus) {
        this.hapus = hapus;
    }
    public List getFullBerita()
    {
        List axc = ejbFacade.getAllBerita();
        return axc;
    }
    public TrBeritaController() {
    }
    
    public List getBeritaDetail()
    {
        List a = ejbFacade.getBeritaDetail(idBeritaDetail);
        
        return ejbFacade.getBeritaDetail(idBeritaDetail);
    }
    
    
    public List getDaftarBerita()
    {
        List a = ejbFacade.findAll();
        
        return a;
    }
    public List getHighLight()
    {
        List a = ejbFacade.getAllBerita();
        return ejbFacade.getAllBerita();
    }
    
    public List getPopuler()
    {
        List a = ejbFacade.getAllPopuler();
        List b = new ArrayList();
        if(a.size()>5)
        {
            for(int x=0;x<a.size();x++)
            {
                if(x==5)
                {
                    return b;
                }
                b.add(a.get(x));
            }
        }
            
        return ejbFacade.getAllPopuler();
    }
    public List getKomentarBanyak()
    {
        List a = ejbFacade.getBeritaKomentar();
        List b = new ArrayList();
        if(a.size()>5)
        {
            for(int x=0;x<a.size();x++)
            {
                if(x==5)
                {
                    return b;
                }
                b.add(a.get(x));
            }
        }
            
        return ejbFacade.getBeritaKomentar();
    }
    public List getBeritaTerbaru() throws ParseException
    {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Calendar tgl =  Calendar.getInstance();
        tgl =Calendar.getInstance();
        tgl.add(Calendar.DATE,-7);
        Date sekarang = null;
        sekarang = tgl.getTime();
        String tanggal = sdf.format(sekarang);
        sekarang = sdf.parse(tanggal);
        List a = ejbFacade.getBeritaLast(sekarang);
        List b = new ArrayList();
        if(a.size()>5)
        {
            for(int x=0;x<a.size();x++)
            {
                if(x==5)
                {
                    return b;
                }
                b.add(a.get(x));
            }
        }
            
        return ejbFacade.getBeritaLast(sekarang);
    }
    public TrBerita getSelected() {
        if (current == null) {
            current = new TrBerita();
            selectedItemIndex = -1;
        }
        return current;
    }

    public int getIdberita() {
        return idberita;
    }

    public void setIdberita(int idberita) {
        this.idberita = idberita;
    }
    
    
    

    private TrBeritaFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public List getAllBerita()
    {
        List<TrBerita> ListA= ejbFacade.findAll();
        for(int a=0;a<ListA.size();a++)
        {
            String kalimat = ListA.get(a).getBerKonten();
            String[] kontenberita = kalimat.split("\\.");
            ListA.get(a).setBerKonten(kontenberita[0]+"."+kontenberita[1]+".");
            
        }
        return ListA;
    }
    
    public String prepareView() {
        current = (TrBerita) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new TrBerita();
        selectedItemIndex = -1;
        return "CreateGambar.xhtml";
    }
    private transient StreamedContent file;

    public StreamedContent getFile() {
        InputStream in = new ByteArrayInputStream(current.getBerKonten().getBytes());
        this.file = new DefaultStreamedContent(in, "text/html", "result.html");
        return file;
    }
    TrBerita idBerita;

    public TrBerita getIdBerita() {
        return idBerita;
    }

    public void setIdBerita(TrBerita idBerita) {
        this.idBerita = idBerita;
    }
    

    public String create() {
        try {
            String a = current.getBerKonten();
            idBerita = current;
            String kalimat = current.getBerKonten();
            String[] kontenberita = kalimat.split("\\. ");
            current.setBerResume(kontenberita[0]+"."+kontenberita[1]+".");
            Date sekarang = new Date();
            current.setBerTglRilis(sekarang);
            current.setBerPengunjung(0);
            getFacade().create(current);
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }
    private List<TrGambarBerita> list;

    public List <TrGambarBerita> getList(){
//        String prodi = (String.valueOf( em.createQuery("SELECT u.prodi FROM Kelas u WHERE u.kodeKelas =:kode")
//                .setParameter("kode",id)
//                .getSingleResult()));
        try{
            int id = idberita;
        List<TrGambarBerita> x = (( em.createQuery("SELECT u FROM TrGambarBerita u WHERE u.gbrBerita.berId = :idberita")
                .setParameter("idberita",idberita)
                .getResultList()));
//        gbBerita = (TrGambarBerita) x;
        return x;
        }catch(Exception e){
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
        
    }

    public void setList(List<TrGambarBerita> list) {
        this.list = list;
    }

    public String prepareEdit() {
        hapus=false;
        current = ejbFacade.find(idberita);
//        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        getList();
        return "Edit";
    }
    
    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TrBeritaUpdated"));
            return "List";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = ejbFacade.find(idberita);
        getFacade().remove(current);
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("TrBeritaDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }
    
    

web/BeritaUser.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <ui:composition template="/templateUserBerita.xhtml">
       

        <ui:define name="ListBerita">
            <h:form>
                <br/><br/>
                <center><h2 style="background-color: #292c2f;box-shadow: 0 1px 1px #ccc;padding: 20px 40px;height: 80px;color: #ffffff;box-sizing: border-box;">Liputan 24 Gobak Sodor</h2></center><br/><br/>
            <div class="body_wrapper">
                <div class="center">
                    <div class="slider">
                      <ul class="bxslider">
                          <p:repeat value="#{trBeritaController.highLight}" var="item">
                              <li><h:graphicImage value="/resources/gambar/#{item[3]}" title="#{item[1]}" style="width: 1200px;height: 500px"/></li>
                          </p:repeat>
                          
                      </ul>
                    </div>
                </div>
            </div><br/><br/>
            <div class="content_area" style="overflow: hidden;margin-left: 30px">
                <div class="main_content ">
                    <div class="left_coloum " style="float: left">
                    <div class="single_left_coloum_wrapper">
                        <h2 class="title" style="font-size: 46px;">Artikel Gobak Sodor</h2>
                        <p:repeat value="#{trBeritaController.highLight}" var="item">
                      <div class="single_left_coloum" style="float: left; margin-top: 20px;margin-left: 25px"> <h:graphicImage value="/resources/gambar/#{item[3]}" alt="" style="width: 300px;height: 300px"/>
                          <h3 style="height: 80px"><h:commandLink action="#{trBeritaController.baca}" value="#{item[1]}" >
                              <f:setPropertyActionListener target="#{trBeritaController.idBeritaDetail}" value="#{item[4]}"/>
                              <f:setPropertyActionListener target="#{trGambarBeritaController.idBeritaDetail}" value="#{item[4]}"/>
                              <f:setPropertyActionListener target="#{trKomentarController.idDetailKomentar}" value="#{item[4]}"/>
                          </h:commandLink></h3>
                          <div ><p><h:outputText value="#{item[5]}" escape="false"/></p></div>
                          <h:commandLink action="#{trBeritaController.baca}" value="Selengkapnya" class="btn btn-primary">
                              <f:setPropertyActionListener target="#{trBeritaController.idBeritaDetail}" value="#{item[4]}"/>
                              <f:setPropertyActionListener target="#{trGambarBeritaController.idBeritaDetail}" value="#{item[4]}"/>
                              <f:setPropertyActionListener target="#{trKomentarController.idDetailKomentar}" value="#{item[4]}"/>
                          </h:commandLink> <br/></div> </p:repeat>
                    </div>


                  </div>
                    <div class="right_coloum" style="float: right">
                        <div class="single_right_coloum">
                          <h2 class="title" style="font-size: 46px;">Paling Populer</h2>
                          <ul>
                              <p:repeat value="#{trBeritaController.populer}" var="item">
                                <li>
                                  <div class="single_cat_right_content">
                                    <h3 style="height: 80px"><h:commandLink action="#{trBeritaController.baca}" value="#{item[1]}" >
                                        <f:setPropertyActionListener target="#{trBeritaController.idBeritaDetail}" value="#{item[2]}"/>
                                        <f:setPropertyActionListener target="#{trGambarBeritaController.idBeritaDetail}" value="#{item[2]}"/>
                                        <f:setPropertyActionListener target="#{trKomentarController.idDetailKomentar}" value="#{item[2]}"/>
                                    </h:commandLink></h3>
                                    <div ><p><h:outputText value="#{item[3]}" escape="false"/></p></div>
                                   <h:commandLink action="#{trBeritaController.baca}" value="Selengkapnya" class="btn btn-primary">
                                        <f:setPropertyActionListener target="#{trBeritaController.idBeritaDetail}" value="#{item[2]}"/>
                                        <f:setPropertyActionListener target="#{trGambarBeritaController.idBeritaDetail}" value="#{item[2]}"/>
                                        <f:setPropertyActionListener target="#{trKomentarController.idDetailKomentar}" value="#{item[2]}"/>
                                    </h:commandLink>
                                  </div>
                                </li>
                              </p:repeat>
                            
                          </ul>
                      </div>
                  
                </div>


            </div>
                </div>
            <br/><br/>
            
           </h:form>
        </ui:define>
    </ui:composition>
</html>

web/CobaAja.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <ui:composition template="/templateBaca_1.xhtml">
        
        <ui:define name="ListBerita">
                <div class="center">
                  <div class="slider">
                      <ul class="bxslider">
                          <p:repeat value="#{trBeritaController.highLight}" var="item">
                              <li><h:graphicImage value="/resources/gambar/#{item[3]}" title="#{item[1]}" style="width: 1200px;height: 500px"/></li>
                          </p:repeat>
                          
                      </ul>
                    </div>
                </div>
             <section class="site-section pt-5">
                <div class="container">
                  <div class="row">
                    <div class="col-md-12">
                        <div>
                            <p:repeat value="#{trBeritaController.beritaDetail}" var="item">
                                <div class="text half-to-full">
                                    <center><h2><h:outputText value="#{item.berJudul}"/></h2></center>
                                    <br/><br/>
                                    <span class="category">Admin</span>
                                    <span class="mr-2"><h:outputText value="#{item.berTglRilis}">
                                        <f:convertDateTime timeZone="GMT+7" pattern="dd MMMMM yyyy" /></h:outputText> </span> &bullet;
                                    <span class="ml-2"><span class="fa fa-comments"></span>   3</span>
                                    <br/><br/>
                                    <h:outputText value="#{item.berKonten}" escape="false"/>
                                </div>
                            </p:repeat>
                        </div>
                    </div>
                  </div>
                  
                </div>


              </section>
        </ui:define>
    </ui:composition>
</html>

web/indexUser.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <ui:composition template="/templateUser.xhtml">
        <ui:define name="Home">
            
        </ui:define>
    </ui:composition>
</html>

web/pagePendaftaranPeserta.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>

        <ui:composition template="./templateAdmin.xhtml">

            <ui:define name="title">
                Registration Participant
            </ui:define>

            <ui:define name="top">
                Registration Participant
            </ui:define>

            <ui:define name="content">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Registration Team</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <h:form enctype="multipart/form-data">
                        <div class="box-body">
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsPesertaLabel_pesId}" for="pesId" />
                                <h:inputText id="pesId" value="#{msPesertaController.selected.pesId}" title="#{bundle.CreateMsPesertaTitle_pesId}" />

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsPesertaLabel_pesNim}" for="pesNim" />
                                <h:inputText id="pesNim" value="#{msPesertaController.selected.pesNim}" title="#{bundle.CreateMsPesertaTitle_pesNim}" required="true" requiredMessage="#{bundle.CreateMsPesertaRequiredMessage_pesNim}"/>

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsPesertaLabel_pesUsernameTim}" for="pesUsernameTim" />
                                <h:inputText id="pesUsernameTim" value="#{msPesertaController.selected.pesUsernameTim}" title="#{bundle.CreateMsPesertaTitle_pesUsernameTim}" />

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsPesertaLabel_pesNamaDepan}" for="pesNamaDepan" />
                                <h:inputText id="pesNamaDepan" value="#{msPesertaController.selected.pesNamaDepan}" title="#{bundle.CreateMsPesertaTitle_pesNamaDepan}" />

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsPesertaLabel_pesNamaBelakang}" for="pesNamaBelakang" />
                                <h:inputText id="pesNamaBelakang" value="#{msPesertaController.selected.pesNamaBelakang}" title="#{bundle.CreateMsPesertaTitle_pesNamaBelakang}" />

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsPesertaLabel_pesTglLahir}" for="pesTglLahir" />
                                <h:inputText id="pesTglLahir" value="#{msPesertaController.selected.pesTglLahir}" title="#{bundle.CreateMsPesertaTitle_pesTglLahir}" >
                                    <f:convertDateTime pattern="MM/dd/yyyy" />
                                </h:inputText>

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsPesertaLabel_pesRole}" for="pesRole" />
                                <h:inputText id="pesRole" value="#{msPesertaController.selected.pesRole}" title="#{bundle.CreateMsPesertaTitle_pesRole}" />

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsPesertaLabel_pesFoto}" for="pesFoto" />
                                <h:inputText id="pesFoto" value="#{msPesertaController.selected.pesFoto}" title="#{bundle.CreateMsPesertaTitle_pesFoto}" />

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsPesertaLabel_pesCreatedby}" for="pesCreatedby" />
                                <h:inputText id="pesCreatedby" value="#{msPesertaController.selected.pesCreatedby}" title="#{bundle.CreateMsPesertaTitle_pesCreatedby}" />

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsPesertaLabel_pesModivedby}" for="pesModivedby" />
                                <h:inputText id="pesModivedby" value="#{msPesertaController.selected.pesModivedby}" title="#{bundle.CreateMsPesertaTitle_pesModivedby}" />

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsPesertaLabel_pesCreateddate}" for="pesCreateddate" />
                                <h:inputText id="pesCreateddate" value="#{msPesertaController.selected.pesCreateddate}" title="#{bundle.CreateMsPesertaTitle_pesCreateddate}" >
                                    <f:convertDateTime pattern="MM/dd/yyyy" />
                                </h:inputText>

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsPesertaLabel_pesModiveddate}" for="pesModiveddate" />
                                <h:inputText id="pesModiveddate" value="#{msPesertaController.selected.pesModiveddate}" title="#{bundle.CreateMsPesertaTitle_pesModiveddate}" >
                                    <f:convertDateTime pattern="MM/dd/yyyy" />
                                </h:inputText>
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <h:commandLink action="#{msPesertaController.create}" class="btn btn-default" value="#{bundle.CreateMsPesertaSaveLink}" />
                        </div>
                    </h:form>
                </div>
                <!-- /.box -->  
            </ui:define>

        </ui:composition>

    </body>
</html>

web/pagePendaftaranTim.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>

        <ui:composition template="./templateAdmin.xhtml">

            <ui:define name="title">
                Registration Team
            </ui:define>

            <ui:define name="top">
                Registration Team
            </ui:define>

            <ui:define name="content">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Registration Team</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <h:form enctype="multipart/form-data">
                        <div class="box-body">
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsTimLabel_timId}" for="timId" />
                                <h:inputText id="timId" value="#{msTimController.selected.timId}" title="#{bundle.CreateMsTimTitle_timId}" />
                            </div>

                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsTimLabel_timEmail}" for="timEmail" />
                                <h:inputText id="timEmail" value="#{msTimController.selected.timEmail}" title="#{bundle.CreateMsTimTitle_timEmail}" />

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsTimLabel_timPassword}" for="timPassword" />
                                <h:inputText id="timPassword" value="#{msTimController.selected.timPassword}" title="#{bundle.CreateMsTimTitle_timPassword}" />

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsTimLabel_timNama}" for="timNama" />
                                <h:inputText id="timNama" value="#{msTimController.selected.timNama}" title="#{bundle.CreateMsTimTitle_timNama}" />

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsTimLabel_timLambang}" for="timLambang" />
                                <h:inputText id="timLambang" value="#{msTimController.selected.timLambang}" title="#{bundle.CreateMsTimTitle_timLambang}" />

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsTimLabel_timCreateby}" for="timCreateby" />
                                <h:inputText id="timCreateby" value="#{msTimController.selected.timCreateby}" title="#{bundle.CreateMsTimTitle_timCreateby}" />

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsTimLabel_timModivedby}" for="timModivedby" />
                                <h:inputText id="timModivedby" value="#{msTimController.selected.timModivedby}" title="#{bundle.CreateMsTimTitle_timModivedby}" />

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsTimLabel_timCreateddate}" for="timCreateddate" />
                                <h:inputText id="timCreateddate" value="#{msTimController.selected.timCreateddate}" title="#{bundle.CreateMsTimTitle_timCreateddate}" >
                                    <f:convertDateTime pattern="MM/dd/yyyy" />
                                </h:inputText>

                            </div>
                            <div class="form-group">
                                <h:outputLabel value="#{bundle.CreateMsTimLabel_timModiveddate}" for="timModiveddate" />
                                <h:inputText id="timModiveddate" value="#{msTimController.selected.timModiveddate}" title="#{bundle.CreateMsTimTitle_timModiveddate}" >
                                    <f:convertDateTime pattern="MM/dd/yyyy" />
                                </h:inputText>
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <h:commandLink action="#{msTimController.create}" class="btn btn-default" value="#{bundle.CreateMsTimSaveLink}" />
                        </div>
                    </h:form>
                </div>
                <!-- /.box -->  
            </ui:define>

        </ui:composition>

    </body>
</html>

web/template.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title><ui:insert name="title">Default Title</ui:insert></title>
        <h:outputStylesheet library="css" name="jsfcrud.css"/>
    </h:head>

    <h:body>
        <h1>
            <ui:insert name="title">Default Title</ui:insert>
        </h1>
        <p>
            <ui:insert name="body">Default Body</ui:insert>
        </p>
    </h:body>

</html>